name: 'Testing:Lab3'
description: 'Action of Lab3 in Testing section'

inputs:
  addition-input-1:
    description: value that will be use with addition script
    required: true
  addition-input-2:
    description: value that will be use with addition script
    required: true
  palindrome-input:
    description: value that will be use with palindrome script
    required: true

outputs:
  addition:
    description: output value for addition
    value: '${{ steps.addition.outputs.outputAdditionValue }}'
  helloWorld:
    description: output value for hello-world
    value: '${{ steps.hello-world.outputs.outputHelloWorldValue }}'
  palindrome:
    description: output value for palindrome
    value: '${{ steps.palindrome.outputs.outputPalindromeValue }}'

runs:
  using: "composite"

  steps: 
      - name: run addition
        id: addition
        env:
          ADD1: ${{ inputs.addition-input-1 }}
          ADD2: ${{ inputs.addition-input-2 }} 
        run: |
          OUTPUT_VALUE=$(sh ${GITHUB_WORKSPACE}/steps/30-testing-lab3-action-workflow-testing-solution/scripts/addition.sh $ADD1 $ADD2)
          echo "::set-output name=outputAdditionValue::$OUTPUT_VALUE"
        shell: bash

      - name: run hello-world
        id: hello-world
        run: |
          OUTPUT_VALUE=$(sh ${GITHUB_WORKSPACE}/steps/30-testing-lab3-action-workflow-testing-solution/scripts/hello-world.sh)
          echo "::set-output name=outputHelloWorldValue::$OUTPUT_VALUE"
        shell: bash

      - name: run palindrome
        id: palindrome
        env:
          PAL: ${{ inputs.palindrome-input }}
        run: |
          OUTPUT_VALUE=$(sh ${GITHUB_WORKSPACE}/steps/30-testing-lab3-action-workflow-testing-solution/scripts/palindrome.sh $PAL)
          echo "::set-output name=outputPalindromeValue::$OUTPUT_VALUE"
        shell: bash

