name: Test the Lab 3 of Testing
on: 
  push:
  workflow_call:
jobs:
  test-testing-lab3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: test
         uses: ./.