name: 'Reusable:Lab'
description: 'Action of the Lab in reusable section'

inputs:
  directory:
    description: 'directory to lint'
    required: true

outputs:
  summary:
    description: summary
    value: ${{ steps.lint.outputs.result }}
 
runs:
  using: "composite"

  steps:  
    - uses: actions/checkout@v3

    - name: install linter
      shell: bash
      run: |
        npm install -g markdownlint-cli

    - name: print markdownlint version
      shell: bash
      run: |
        echo $(markdownlint -V)

    - name: lint makdown
      shell: bash
      continue-on-error: true
      run: |
        markdownlint ${{ inputs.directory }}/*.md -o tmp.txt

    - name: Format result
      id: lint
      uses: actions/github-script@v5
      with:
        github-token: $GITHUB_TOKEN
        result-encoding: string
        script: |
          const fs = require('fs').promises;
          var reportBulk = (await fs.readFile("tmp.txt")).toString();
          const output = `#### Lint 📖
          <details> 
          \`\`\`
          `+reportBulk+`
          \`\`\`
          </details>`
          return reportBulk;
