name: Runs Reusable Workflow
description: Example of composite action calling a reusable workflow
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    # This should failed due to system limitation
    - uses: ./.github/workflows/syntax.yaml
