name: Road to the marketplace
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.

  release:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v
      - uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ github.token }}
